[package]
name = "mirror-rdb"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror.workspace = true
log.workspace = true
tokio = { workspace = true, features = ["full"] }
sqlx = { workspace = true, features = ["runtime-tokio", "tls-rustls-aws-lc-rs", "postgres", "uuid", "chrono", "json"] }
env_logger.workspace = true
clap = { workspace = true, features = ["derive", "cargo", "env"] }
clap-verbosity-flag.workspace = true
anyhow = { workspace = true, features = ["backtrace"] }
gisst.workspace = true
rdb-sys.workspace = true
