[package]
name = "ingest"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir.workspace = true
uuid = { workspace = true, features = ["serde", "v4"] }
thiserror.workspace = true
log.workspace = true
tokio = { workspace = true, features = ["full"] }
sqlx = { workspace = true, features = ["runtime-tokio", "tls-rustls-aws-lc-rs", "postgres", "uuid", "chrono", "json"] }
env_logger.workspace = true
clap = { workspace = true, features = ["derive", "cargo", "env"] }
clap-verbosity-flag.workspace = true
anyhow = { workspace = true, features = ["backtrace"] }
gisst.workspace = true
rdb-sys.workspace = true
chrono = { workspace = true, features = ["clock"] }
md-5.workspace = true
digest-io.workspace = true
base16ct                = { workspace = true, features = ["alloc"] }
regex.workspace = true
rayon.workspace = true
chd.workspace = true
