[database]
database_url = "postgresql://postgres:postgres@localhost/gisstdb"

[http]
listen_address = "0.0.0.0"
listen_port = 3000

[storage]
root_folder_path = "./storage"
temp_folder_path = "./tmp"
folder_depth = 4