[database]
database_url = "postgresql://postgres:postgres@localhost/gisstdb"
max_connections = 128
min_connections = 8
connect_timeout_seconds = 30
idle_timeout_seconds = 900
max_lifetime_seconds = 3600

[http]
listen_address = "0.0.0.0"
listen_port = 3000

[storage]
root_folder_path = "./storage"
temp_folder_path = "./tmp"
folder_depth = 4

[debug]
log_level = 3
log_to_file = true  
log_to_terminal = true  
log_path = "./logs"  
log_rolling_type = "daily"  
