[database]
database_url = "postgresql://postgres:postgres@localhost/gisstdb"
max_connections = 128
min_connections = 8
connect_timeout_seconds = 30
idle_timeout_seconds = 900
max_lifetime_seconds = 3600

[http]
listen_address = "0.0.0.0"
listen_port = 3000
dev_cert = "../test-cert/cert.pem"
dev_key = "../test-cert/dev.pem"
dev_ssl = true
base_url = "https://localhost:3000"

[storage]
root_folder_path = "./storage"
temp_folder_path = "./tmp"
folder_depth = 4

[env]
default_directive = "gisst_server=debug"
rust_log = "tower_http=debug,gisst_server=debug,gisst=debug"
trace_include_headers = false