global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:8888']

  - job_name: 'node_exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['node_exporter:9100']
