global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:8888']

  - job_name: 'node_exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: postgres
    static_configs:
      - targets: ["psql_exporter:9187"]

otlp:
    promote_resource_attributes:
        - service.instance.id
        - service.name
        - service.namespace
        - deployment.environment
        - k8s.namespace.name
        - k8s.pod.name
    keep_identifying_resource_attributes: true
