default_install_hook_types: [pre-commit, pre-push]
repos:
  - repo: https://code.forgejo.org/forgejo/runner
    rev: v11.1.1
    hooks:
    - id: forgejo-runner-validate
  - repo: local
    hooks:
      - id: sqlx
        name: sqlx
        description: Check that sqlx prepare has been run
        entry: hooks/backend-sqlx.sh
        language: unsupported_script
        files: ^backend/
        types_or: [sql, rust]
        pass_filenames: false
      - id: rustfmt
        name: rustfmt
        description: Check if all files follow the rustfmt style
        entry: hooks/backend-rustfmt.sh
        language: unsupported_script
        pass_filenames: false
        files: ^backend/
        types: [rust,toml]
        stages: [pre-push]
      - id: clippy
        name: clippy
        description: Run clippy
        entry: hooks/backend-clippy.sh
        language: unsupported_script
        pass_filenames: false
        files: ^backend/
        types: [rust,toml]
        stages: [pre-push]
      - id: frontend-check
        name: frontend check
        description: Run frontend checks
        language: unsupported_script
        entry: hooks/frontend-check.sh
        files: ^frontend/
        stages: [pre-push]
