FROM mcr.microsoft.com/devcontainers/universal:5

RUN apt-get update && apt-get install -y \
  libssl-dev nginx \
  libatk1.0-0t64 libatk-bridge2.0-0t64 libcups2t64 \
  libxkbcommon0 libatspi2.0-0t64 libxcomposite1 \
  libxdamage1 libxfixes3 libxrandr2 libgbm1 libasound2t64 \
  postgresql-client

USER codespace

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y -c rust-analyzer,rust-src,rustfmt,clippy,rust-docs
ENV PATH="/home/codespace/.cargo/bin:${PATH}"
RUN cargo install sqlx-cli
