[workspace]
members = ["gisst", "gisst-server", "gisst-cli", "ingest", "rdb-sys"]
resolver = "2"

[profile.dev.package.md5]
opt-level = 3
[profile.dev.package.sqlx-macros]
opt-level = 3
# [profile.dev]
# debug=line-tables-only
