[workspace]
members = ["gisst", "gisst-server", "gisst-cli", "ingest", "mirror-rdb", "rdb-sys", "vendor/bincode_derive", "vendor/bincode", "vendor/mbrman"]
resolver = "2"

[workspace.package]
version = "0.2.4"
edition = "2024"
license = "AGPL-3.0-or-later"

#[profile.dev]
#debug = 0

[profile.dev.package.md-5]
opt-level = 3
[profile.dev.package.sqlx-macros]
opt-level = 3
# [profile.dev]
# debug=line-tables-only

