services:
  jaeger:
    image: jaegertracing/jaeger:${JAEGER_VERSION:-latest}
    container_name: jaeger
    user: "${UID}:${GID}"
    environment:
      QUERY_BASE_PATH: $QUERY_BASE_PATH
    networks:
      backend:
      frontend:
    volumes:
      - type: bind
        source: ./docker-configs/jaeger-ui.json
        target: /etc/jaeger/jaeger-ui.json
      - type: bind
        source: ./docker-configs/config-spm.yaml
        target: /etc/jaeger/config.yml
      - "jaeger-storage:/jaeger:rw"
    command: ["--config", "/etc/jaeger/config.yml", "--set=extensions.jaeger_query.base_path=${QUERY_BASE_PATH}"]
    ports:
      - "16686:16686"
      - "8888:8888"
      - "8889:8889"
      - "4317:4317"
      - "4318:4318"

  prometheus:
    image: prom/prometheus:v3.2.0
    container_name: prometheus
    networks:
      - backend
      - frontend
    command: [ "--web.enable-otlp-receiver", "--enable-feature=otlp-write-receiver", "--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus" ]
    volumes:
      - type: bind
        source: ./docker-configs/prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - "prometheus-storage:/prometheus:rw"
    ports:
      - "9090:9090"

  psql_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: psql_exporter
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - type: bind
        source: ./docker-configs/dbpasswd
        target: /var/pgx/dbpasswd
    environment:
      DATA_SOURCE_URI: 172.17.0.1:5432/postgres?sslmode=disable
      DATA_SOURCE_USER: grafanareader
      DATA_SOURCE_PASS_FILE: /var/pgx/dbpasswd
    command:
      - "--web.listen-address=0.0.0.0:9187"
      - "--collector.stat_statements"
    ports:
      - "9187:9187"

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    networks:
      - backend
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.rootfs=/rootfs'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--web.listen-address=0.0.0.0:9100'
    ports:
      - '9100:9100'

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      GF_SERVER_PROTOCOL: $GF_SERVER_PROTOCOL 
      GF_SERVER_ROOT_URL: $GF_SERVER_ROOT_URL
      GF_SERVER_DOMAIN: $GF_SERVER_DOMAIN
      GF_SERVER_SERVE_FROM_SUB_PATH: $GF_SERVER_SERVE_FROM_SUB_PATH
      GF_AUTH_PROXY_ENABLED: $GF_AUTH_PROXY_ENABLED
      GF_AUTH_PROXY_HEADERNAME: $GF_AUTH_PROXY_HEADERNAME
      GF_AUTH_PROXY_AUTO_SIGN_UP: $GF_AUTH_PROXY_AUTO_SIGN_UP
    networks:
      - backend
    extra_hosts:
      docker.host.internal: host-gateway
    volumes:
      - "grafana-storage:/var/lib/grafana:rw"
    ports:
      - '3003:3000'

volumes:
  prometheus-storage:
  jaeger-storage:
  grafana-storage:

networks:
  backend:
  frontend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
