name: Release

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-24.04
    container:
      image: cafe.cs.pomona.edu/shftgroup/gisst-ci:latest
    steps:
    - uses: actions/checkout@v6
    - name: Pull cached backend dependencies
      run: mv /tmp/backend/target backend/
    - name: Restore cached node modules
      run: |
        mv /tmp/frontend/node_modules frontend/
        cd frontend
        npm i
    - name: npm ci
      run: npm ci
      working-directory: frontend
    - name: build
      run: npm run build --workspaces --if-present
      working-directory: frontend
    - name: dist
      run: npm run dist --workspaces --if-present
      working-directory: frontend
    - name: Build cli tools
      working-directory: backend
      run: cargo build --all-targets --release
    - name: tgz assets
      working-directory: backend
      run: tar czvf ../gisst-assets.tgz ./*-dist ./config ./v86dump.js env.template ../manifest.json ./gisst-server/src/templates ./docker-compose.yml ./docker-configs ./meili/README.org ./etc
    - name: tgz examples
      working-directory: backend
      run: tar czvf ../examples.tgz ./examples ./load_examples.sh
    - name: package binaries
      run: |
        mkdir -p bin
        find backend/target/release -maxdepth 1 -type f -executable -exec cp \{\} bin \;
        tar czvf bin-linux-${{ runner.arch }}.tgz ./bin
        echo bin-linux-${{ runner.arch }}.tgz
    - name: Stage release files
      run: |
        mkdir release
        cp bin-linux-${{ runner.arch }}.tgz release
        cp gisst-assets.tgz release
        cp examples.tgz release
    - name: Release
      uses: https://code.forgejo.org/actions/forgejo-release@v2.12.1
      with:
        direction: upload
        override: true
        body: "These packages do not include built core files, since those might require BIOS files or other copyrighted material. You can build them yourself with `docker run --rm -v $(pwd)/build:/out -v $(pwd)/manifest.json:/manifest.json -v $(pwd)/v86bios:/files/v86bios -v $(pwd)/psxbios:/files/psxbios -e GET_ASSETS=0 cafe.cs.pomona.edu/shftgroup/gisst-dist:latest`."
        release-dir: release
