name: Run Tests

on:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  GISST_CONFIG: "./"
  GISST_CONFIG_PATH: "./config"
  MEILI_URL: "http://localhost:7700"
  MEILI_MASTER_KEY: "test-api-key-github-actions"
  MEILI_API_KEY: "test-api-key-github-actions"
  MEILI_SEARCH_KEY: "test-api-key-github-actions"
  GISST_CI: "true"
  DATABASE_URL: "postgresql://postgres:postgres@localhost/gisstdb"
  LOAD_WIN: "0"
  STOP_ON_ERR: "true"
  SQLX_OFFLINE: 1

jobs:
  cores:
    runs-on: ubuntu-24.04
    container:
      image: cafe.cs.pomona.edu/shftgroup/gisst-ci:latest
    outputs:
      core-hash: ${{ steps.hash-manifest.outputs.hash }}
    steps:
    - uses: actions/checkout@v6
    # TODO: move ci cores and examples into a generic shftgroup
    # package produced by a private repository (and generate example
    # envs automatically?).  it should also create a release on its
    # own releases page for the package that includes copyrighted
    # material. Basically, cores (even for CI) should be versioned
    # separately from gisst in part because permissions are different.
    # If it's a private, owner only repo with no PRs or PRs limited to
    # owners then we also can be chill about docker in that repo
    - name: Compute core manifest hash
      id: hash-manifest
      uses: https://gitea.com/seepine/hash-files@v1
      with:
        patterns: |
          manifest-ci.json
          dist-update-docker.sh
    - name: Check cached cores
      id: cache
      uses: actions/cache/restore@v5
      with:
        path: ./build
        key: "cache-${{ steps.hash-manifest.outputs.hash }}"
        lookup-only: true
    - name: Run dist script using ci dist image
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p build
        OUT_DIR="${PWD}/build" FILE_ROOT="$PWD" MANIFEST_FILE="${PWD}/manifest-ci.json" GET_ASSETS=0 ./dist-update-docker.sh
    - name: Cache cores
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v5
      with:
        path: ./build
        key: "cache-${{ steps.hash-manifest.outputs.hash }}"
  frontend:
    runs-on: ubuntu-24.04
    container:
      image: cafe.cs.pomona.edu/shftgroup/gisst-ci:latest
    env:
      GISST_CONFIG_PATH: ./config
      MEILI_URL: http://localhost:7701
      MEILI_MASTER_KEY: test-api-key
      MEILI_API_KEY: test-api-key
    steps:
    - uses: actions/checkout@v6
    - name: Pull cached backend dependencies
      run: mv /tmp/backend/target backend/
    - name: Restore cached node modules
      run: |
        mv /tmp/frontend/node_modules frontend/
        cd frontend
        npm i
    - name: build
      run: npm run build --workspaces --if-present
      working-directory: frontend
    - name: tsc
      run: npm run check --workspaces --if-present
      working-directory: frontend
    - name: dist
      run: npm run dist --workspaces --if-present
      working-directory: frontend
    - uses: https://github.com/JarvusInnovations/background-action@v1
      name: Run meili
      with:
        run: |
          meilisearch --no-analytics --master-key ${{ env.MEILI_MASTER_KEY }} --env development --db-path ./test --http-addr localhost:7701 &
        wait-on: '{"resources":["http-get://localhost:7701/version"],"headers":{"Authorization":"Bearer ${{ env.MEILI_API_KEY }}"}}'
        tail: true # true = stderr,stdout
        log-output-resume: stderr
        wait-for: 1m
        log-output: stderr,stdout # same as true
        log-output-if: failure
        working-directory: backend/meili
    - name: Create meili index # TODO: this should be factored into a different rust crate because it doesn't strictly need a lot of dependencies, but we'll pay the build time cost twice during CI
      working-directory: backend
      run: cargo run --bin gisst-cli -- init-indices
    - name: Create test data
      working-directory: frontend/server-ui
      run: node scripts/gendata.js $MEILI_URL
    - name: ensure playwright binaries present
      run: npx playwright install
      working-directory: frontend
    - name: test
      run: npm run test --workspaces --if-present
      working-directory: frontend
    - uses: actions/upload-artifact@v3
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: frontend/playwright-report/
        retention-days: 15
  backend:
    needs:
      - cores
    runs-on: ubuntu-24.04
    container:
      image: cafe.cs.pomona.edu/shftgroup/gisst-ci:latest
    steps:
    - uses: actions/checkout@v6
    - name: Get cached cores
      uses: actions/cache/restore@v5
      with:
        path: ./build
        key: "cache-${{ needs.outputs.core-hash }}"
        fail-on-cache-miss: true
    - name: Pull cached backend dependencies
      run: mv /tmp/backend/target backend/
    - name: Clippy
      working-directory: backend
      run: |
        cargo clippy --all-features --all-targets -- -Dwarnings -Dclippy::pedantic
        cargo clippy --all-targets -- -Dwarnings -Dclippy::pedantic
    - name: Run meili
      uses: https://github.com/JarvusInnovations/background-action@v1
      with:
        run: meilisearch --no-analytics --master-key ${{ env.MEILI_MASTER_KEY }} --env development &
        wait-on: '{"resources":["http-get://localhost:7700/version"],"headers":{"Authorization":"Bearer test-api-key-github-actions"}}'
        tail: true # true = stderr,stdout
        log-output-resume: stderr
        wait-for: 1m
        log-output: stderr,stdout # same as true
        log-output-if: failure
        working-directory: backend/meili
    - name: Run postgres
      run: |
        sudo service postgresql start
        sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"
    - name: Load example data into DB
      working-directory: backend
      run: |
        rm -rf storage && mkdir storage
        touch .env
        cargo sqlx database reset -y -f
        zsh -e ./load_examples.sh
    - name: Test
      working-directory: backend
      run: |
        cargo test --workspace --all-targets
        cargo test --workspace --all-features --all-targets
