[package]
name = "gisst-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default=[]
dummy_auth=[]
fatfs_logging=["gisst/fatfs_logging"]

[dependencies]
anyhow.workspace = true
axum = { workspace = true, features = ["multipart", "macros"] }
axum-server = { workspace = true, features = ["tls-rustls"] }
base64.workspace = true
rustls.workspace = true
bytes = { workspace = true, features = ["serde"] }
config = { workspace = true, features = ["toml"] }
futures.workspace = true
sqlx = { workspace = true, features = ["migrate", "runtime-tokio", "tls-rustls-aws-lc-rs", "postgres", "uuid", "chrono", "json", "macros"] }
minijinja = { workspace = true, features = ["builtins", "macros", "json", "loader", "urlencode"] }
secrecy = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["raw_value"] }
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tower = { workspace = true, features = ["util"] }
tower-http = { workspace = true, features = ["fs", "trace", "cors"] }
tracing = { workspace = true, features = ["attributes"] }
tracing-subscriber = { workspace = true, features = ["env-filter", "registry"] }
uuid = { workspace = true, features = ["serde", "v4"] }
gisst.workspace = true
serde_with = { workspace = true, features = ["base64"] }
chrono = { workspace = true, features = ["clock"] }
axum-login.workspace = true
tower-sessions = { workspace = true, features = ["memory-store", "axum-core"] }
oauth2.workspace = true
oauth2-reqwest.workspace = true
reqwest = { workspace = true, features = ["json", "charset", "rustls", "http2", "system-proxy"] }
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
opentelemetry-otlp = { workspace = true, features = ["grpc-tonic", "default"] }
opentelemetry-stdout.workspace = true
opentelemetry-semantic-conventions = { workspace = true, features = ["default", "semconv_experimental"] }
tracing-opentelemetry.workspace = true
axum-extra = { workspace = true, features = ["query", "tracing"] }
