[package]
name                    = "gisst"
version                 = "0.1.0"
edition                 = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx                    = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "uuid", "time", "json"] }
time                    = { version = "0.3.21", features = ["serde", "parsing"] }
uuid                    = { version = "1.3.1", features = ["serde", "v4"] }
serde                   = { version = "1.0.159", features = ["derive"] }
serde_json              = { version = "1.0.96", features = ["raw_value"] }
thiserror               = "1.0.40"
async-trait             = "0.1.68"
log                     = "0.4.17"
tokio                   = { version = "1.27.0", features = ["full"] }
md5                     = "0.7.0"
bytes                   = { version = "1.4.0", features = ["serde"] }
config                  = { version = "0.13.3", features = ["toml"], default-features = false }
async-compression       = { version = "0.4", features = ["tokio", "gzip", "zstdmt"] }