[package]
name                    = "gisst"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default=[]
fatfs_logging=["fatfs/log_level_trace"]

[dependencies]
sqlx = { workspace = true, features = ["migrate", "runtime-tokio", "tls-rustls-aws-lc-rs", "postgres", "uuid", "chrono", "json", "macros", "bigdecimal"] }
uuid                    = { workspace = true, features = ["serde", "v4"] }
serde                   = { workspace = true, features = ["derive"] }
thiserror.workspace = true
log.workspace = true
tokio                   = { workspace = true, features = ["full"] }
md-5.workspace = true
digest-io.workspace = true
base16ct                = { workspace = true, features = ["alloc"] }
bytes                   = { workspace = true, features = ["serde"] }
async-compression       = { workspace = true, features = ["tokio", "gzip"] }
chrono = { workspace = true, features = ["serde"] }
serde_with = { workspace = true, features = ["base64"] }
tracing.workspace = true
tree_magic_mini = { workspace = true, features = ["with-gpl-data"] }
fatfs = { git = "https://github.com/rafalh/rust-fatfs/", rev = "c4b88477b22ca7e5131fbd8891f62a5deaa88e6e" }
mbrman.workspace = true
fscommon.workspace = true
zip = { workspace = true, features = ["deflate"] }
opentelemetry.workspace = true
num-traits.workspace = true
meilisearch-sdk = { workspace = true, features = ["jwt_aws_lc_rs"] }
reqwest = { workspace = true, features = ["stream", "json", "charset", "rustls", "http2", "system-proxy"] }
futures.workspace = true
futures-core.workspace = true
futures-io.workspace = true
pin-project-lite.workspace = true
yaup.workspace = true
async-trait.workspace = true
