-- Add down migration script here

ALTER TABLE IF EXISTS creator ALTER COLUMN created_on DROP NOT NULL;
ALTER TABLE IF EXISTS users ALTER COLUMN creator_id DROP NOT NULL;
ALTER TABLE IF EXISTS environment ALTER COLUMN created_on DROP NOT NULL;
ALTER TABLE IF EXISTS file ALTER COLUMN created_on DROP NOT NULL;
ALTER TABLE IF EXISTS image ALTER COLUMN created_on DROP NOT NULL;
ALTER TABLE IF EXISTS instance ALTER COLUMN created_on DROP NOT NULL;
ALTER TABLE IF EXISTS object ALTER COLUMN created_on DROP NOT NULL;
ALTER TABLE IF EXISTS replay ALTER COLUMN created_on DROP NOT NULL;
ALTER TABLE IF EXISTS save ALTER COLUMN created_on DROP NOT NULL;
ALTER TABLE IF EXISTS state ALTER COLUMN created_on DROP NOT NULL;
ALTER TABLE IF EXISTS state ALTER COLUMN creator_id DROP NOT NULL;
ALTER TABLE IF EXISTS state ALTER COLUMN screenshot_id DROP NOT NULL;
ALTER TABLE IF EXISTS work ALTER COLUMN created_on DROP NOT NULL;
