[package]
name = "rdb-sys"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base16ct                = { workspace = true, features = ["alloc"] }



[build-dependencies]
cc.workspace = true
