services:
  devcontainer:
    image: cafe.cs.pomona.edu/shftgroup/gisst-dev:latest
    env_file:
      - ./devcontainer.env
    environment:
      PODMAN_USERNS: keep-id
      SSH_AUTH_SOCK: "/run/ssh.sock"
    volumes:
      - ../:/workspace:cached,Z
      - ./certs:/certs:Z
      - source: "${SSH_AUTH_SOCK}"
        target: "/run/ssh.sock"
        type: bind
    command: sleep infinity
    expose:
      - "3000"
      - "5173"
    ports:
      - "3000:443"
      - "3000:443/udp"
      - "5173:5173"
    depends_on:
      - db
      - meili
      - meilitest
    links:
      - db
      - meili
      - meilitest
  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: gisstdb
    expose:
      - "5432"
    ports:
      - "5432:5432"
  meili:
    image: getmeili/meilisearch:latest
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: devcontainer_testkey
    volumes:
      - meili-data:/meili_data
    expose:
      - "7700"
    ports:
      - "7700:7700"
  meilitest:
    image: getmeili/meilisearch:latest
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: test-api-key
    expose:
      - "7701"
    ports:
      - "7701:7700"
volumes:
  postgres-data:
  meili-data:
