[package]
name = "gisst-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir.workspace = true
config = { workspace = true, features = ["toml"] }
uuid = { workspace = true, features = ["serde", "v4"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["raw_value"] }
sqlx = { workspace = true, features = ["runtime-tokio", "tls-rustls-aws-lc-rs", "postgres", "uuid", "chrono", "json"] }
tokio = { workspace = true, features = ["full"] }
thiserror.workspace = true
log.workspace = true
env_logger.workspace = true
clap = { workspace = true, features = ["derive", "cargo", "env"] }
clap-verbosity-flag.workspace = true
anyhow.workspace = true
gisst.workspace = true
chrono = { workspace = true, features = ["clock"] }
