name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - name: Create SSH key
    #   run: |
    #     mkdir -p ~/.ssh/
    #     echo "$SSH_PRIVATE_KEY" > ../private.key
    #     sudo chmod 600 ../private.key
    #     echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    #   shell: bash
    #   env:
    #     SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
    #     SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
    #     SSH_KEY_PATH: ${{ github.workspace }}/../private.key
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.5.1
      with:
        workspaces: "backend"
    - name: Build backend
      working-directory: backend
      run: cargo build --release
    - name: Download web-dist
      uses: actions/download-artifact@v3
      with:
        name: web-dist
    # - name: Deploy server
    #   run: rsync -avzh --rsh "ssh -J jcoa2018@cafe.cs.pomona.edu" frontend-web/dist jcoa2018@gisst.pomona.edu:~/embedulator/frontend-web/
    #   run: rsync -avzh --rsh "ssh -J jcoa2018@cafe.cs.pomona.edu" backend/ jcoa2018@gisst.pomona.edu:~/embedulator/frontend-web/
    #   run: rsync -avzh --rsh "ssh -J jcoa2018@cafe.cs.pomona.edu" frontend-web jcoa2018@gisst.pomona.edu:~/embedulator
    
