# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache node modules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        cache-dependency-path: '**/package-lock.json'
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: ci
      run: npm ci
      working-directory: frontend
    - name: build
      run: npm run build --workspaces --if-present
      working-directory: frontend
    - name: tsc
      run: npm run check
      working-directory: frontend
    # - name: upload frontend-web/dist
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: web-dist
    #     path: frontend/frontend-web/dist
    #     retention-days: 1
