name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.5.1
      with:
        workspaces: "backend"
    - name: Clippy
      uses: giraffate/clippy-action@v1
      with:
        clippy_flags: -- -Dwarnings
        reporter: 'github-pr-review'
        workdir: backend
