name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.5.1
      with:
        workspaces: "backend"
    - name: Install magic
      run: sudo apt-get install -y libmagic-dev
    - name: Clippy
      working-directory: backend
      run: cargo clippy --all-features --all-targets -- -Dwarnings -Dclippy::pedantic
